### PR TITLE
feat: Add Dockerfile for stamping

### PR DESCRIPTION
**Pull request by miiila**
To prevent platform specific requirements, let's use Docker!

### CODE REVIEW

**Comment by Werkov** [comment]
What a practical idea.

1) Why did you use (relatively) old base image Ubuntu 16.04? (I can run scripts natively on 18.04 and I think it's better to use the most recent version that isn't broken :-), which helps resolving possible future issues.)

2) Would you add a paragraph into README about the containerized use? (It'll come handy to future orgs, not familiar with Docker (I struggled a bit with proper directory paths.)

**Review by Werkov — COMMENTED** [review]
What a practical idea.

1) Why did you use (relatively) old base image Ubuntu 16.04? (I can run scripts natively on 18.04 and I think it's better to use the most recent version that isn't broken :-), which helps resolving possible future issues.)

2) Would you add a paragraph into README about the containerized use? (It'll come handy to future orgs, not familiar with Docker (I struggled a bit with proper directory paths.)

**Comment by miiila** [comment]
1. Last year, when we were running this, I struggled to run it on anything else than 16.04, because of pdftk had been removed (because of some JDK dependency; details at https://askubuntu.com/questions/1028522/how-can-i-install-pdftk-in-ubuntu-18-04-and-later). It may have improved, but I didn't want to go to the rabbit hole of trial and error :-) I can try to modify it after current event.

2. Yeah, I wanted to do that. Thanks for reminding, it's done now.

**Comment by Werkov** [comment]
Thank you! Merged (and filed #2 for tracking).

**Pull request merged**
